# Generated by Django 4.2.3 on 2023-08-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphQLapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="owner",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
