# Generated by Django 4.2.3 on 2023-08-04 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("graphQLapi", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cartItems",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="graphQLapi.cartitem",
            ),
        ),
    ]
